### ISSUE TITLE
可不可以写一下如何调用？

### ISSUE THREAD

**Issue by litengfei-ff** [lei-zhu/SimpleCrawler#1]
可不可以举例写一下如何调用？对爬虫不是很了解

**Comment by litengfei-ff** [comment]
CrawlSetting类中的 SeedsAddress 属性应该可以在外部进行赋值

public List<string> SeedsAddress { get;  /* private */  set; }

**Comment by lei-zhu** [comment]
可以，我明天就把demo放上来

**Comment by lei-zhu** [comment]
SeedsAddress 类型是 List<string>，在构造函数内已经初始化了，外部只需要使用 List 类型提供的操作方法就可以了，所以是 private set

**Comment by lei-zhu** [comment]
demo 已经放上来了可以看下

**Comment by litengfei-ff** [comment]
见笑了，，，
学习中。。。。。。。

**Comment by lei-zhu** [comment]
都有一个过程，慢慢来
